import { db } from '@/db';
import { communityPosts } from '@/db/schema';

async function main() {
    const samplePosts = [
        {
            userId: 1,
            authorName: 'Sarah Johnson',
            authorAvatar: 'https://i.pravatar.cc/150?img=1',
            content: 'Just hit my first 5K PR! Ran it in 28:45 - feeling amazing! 🏃‍♀️',
            category: 'Achievement',
            likes: 42,
            createdAt: new Date('2024-11-15T08:30:00').toISOString(),
            updatedAt: new Date('2024-11-15T08:30:00').toISOString(),
        },
        {
            userId: 2,
            authorName: 'Mike Chen',
            authorAvatar: 'https://i.pravatar.cc/150?img=2',
            content: 'Finally benched 200 lbs today! 6 months of consistent training paid off 💪',
            category: 'Achievement',
            likes: 38,
            createdAt: new Date('2024-11-18T14:20:00').toISOString(),
            updatedAt: new Date('2024-11-18T14:20:00').toISOString(),
        },
        {
            userId: 3,
            authorName: 'Emma Davis',
            authorAvatar: null,
            content: 'Lost 10 pounds this month through consistent meal prep and tracking',
            category: 'Achievement',
            likes: 45,
            createdAt: new Date('2024-11-22T10:15:00').toISOString(),
            updatedAt: new Date('2024-11-22T10:15:00').toISOString(),
        },
        {
            userId: 4,
            authorName: 'James Wilson',
            authorAvatar: 'https://i.pravatar.cc/150?img=4',
            content: "What's your favorite pre-workout snack? Looking for new ideas",
            category: 'Question',
            likes: 15,
            createdAt: new Date('2024-11-20T07:45:00').toISOString(),
            updatedAt: new Date('2024-11-20T07:45:00').toISOString(),
        },
        {
            userId: 5,
            authorName: 'Lisa Anderson',
            authorAvatar: 'https://i.pravatar.cc/150?img=5',
            content: 'Best stretches for lower back pain after deadlifts?',
            category: 'Question',
            likes: 22,
            createdAt: new Date('2024-11-25T16:30:00').toISOString(),
            updatedAt: new Date('2024-11-25T16:30:00').toISOString(),
        },
        {
            userId: 1,
            authorName: 'Sarah Johnson',
            authorAvatar: 'https://i.pravatar.cc/150?img=1',
            content: 'How do you stay motivated on rest days?',
            category: 'Question',
            likes: 18,
            createdAt: new Date('2024-11-28T09:00:00').toISOString(),
            updatedAt: new Date('2024-11-28T09:00:00').toISOString(),
        },
        {
            userId: 2,
            authorName: 'Mike Chen',
            authorAvatar: null,
            content: 'Meal prep Sunday success! High protein, low carb bowls ready for the week 🥗',
            category: 'Nutrition',
            likes: 33,
            createdAt: new Date('2024-11-17T13:20:00').toISOString(),
            updatedAt: new Date('2024-11-17T13:20:00').toISOString(),
        },
        {
            userId: 3,
            authorName: 'Emma Davis',
            authorAvatar: 'https://i.pravatar.cc/150?img=3',
            content: 'Discovered this amazing protein smoothie recipe - 40g protein, tastes like dessert!',
            category: 'Nutrition',
            likes: 41,
            createdAt: new Date('2024-11-21T11:45:00').toISOString(),
            updatedAt: new Date('2024-11-21T11:45:00').toISOString(),
        },
        {
            userId: 4,
            authorName: 'James Wilson',
            authorAvatar: 'https://i.pravatar.cc/150?img=4',
            content: 'Remember: progress over perfection. Every workout counts! 💯',
            category: 'Motivation',
            likes: 37,
            createdAt: new Date('2024-11-19T06:30:00').toISOString(),
            updatedAt: new Date('2024-11-19T06:30:00').toISOString(),
        },
        {
            userId: 5,
            authorName: 'Lisa Anderson',
            authorAvatar: null,
            content: "Bad workout > No workout. Show up even when you don't feel like it",
            category: 'Motivation',
            likes: 44,
            createdAt: new Date('2024-11-24T15:00:00').toISOString(),
            updatedAt: new Date('2024-11-24T15:00:00').toISOString(),
        },
        {
            userId: 1,
            authorName: 'Sarah Johnson',
            authorAvatar: 'https://i.pravatar.cc/150?img=1',
            content: 'Completed my first half marathon today! Training for 3 months was totally worth it 🎉',
            category: 'Achievement',
            likes: 39,
            createdAt: new Date('2024-11-26T17:30:00').toISOString(),
            updatedAt: new Date('2024-11-26T17:30:00').toISOString(),
        },
        {
            userId: 2,
            authorName: 'Mike Chen',
            authorAvatar: 'https://i.pravatar.cc/150?img=2',
            content: 'Anyone have tips for improving flexibility? Struggling with hip mobility',
            category: 'Question',
            likes: 19,
            createdAt: new Date('2024-11-27T12:15:00').toISOString(),
            updatedAt: new Date('2024-11-27T12:15:00').toISOString(),
        },
        {
            userId: 3,
            authorName: 'Emma Davis',
            authorAvatar: 'https://i.pravatar.cc/150?img=3',
            content: 'Greek yogurt + berries + honey = perfect post-workout snack. Simple and delicious!',
            category: 'Nutrition',
            likes: 28,
            createdAt: new Date('2024-11-23T14:40:00').toISOString(),
            updatedAt: new Date('2024-11-23T14:40:00').toISOString(),
        },
        {
            userId: 4,
            authorName: 'James Wilson',
            authorAvatar: null,
            content: 'Your only competition is who you were yesterday. Keep pushing forward! 🔥',
            category: 'Motivation',
            likes: 35,
            createdAt: new Date('2024-11-16T08:00:00').toISOString(),
            updatedAt: new Date('2024-11-16T08:00:00').toISOString(),
        },
        {
            userId: 5,
            authorName: 'Lisa Anderson',
            authorAvatar: 'https://i.pravatar.cc/150?img=5',
            content: 'New personal record on squats - 185 lbs for 5 reps! Never giving up on leg day 🦵',
            category: 'Achievement',
            likes: 31,
            createdAt: new Date('2024-11-29T10:45:00').toISOString(),
            updatedAt: new Date('2024-11-29T10:45:00').toISOString(),
        },
        {
            userId: 1,
            authorName: 'Sarah Johnson',
            authorAvatar: null,
            content: 'Best time to take creatine - before or after workout? What does the science say?',
            category: 'Question',
            likes: 12,
            createdAt: new Date('2024-12-01T09:30:00').toISOString(),
            updatedAt: new Date('2024-12-01T09:30:00').toISOString(),
        },
        {
            userId: 2,
            authorName: 'Mike Chen',
            authorAvatar: 'https://i.pravatar.cc/150?img=2',
            content: 'Meal timing matters! Eating within 30 mins post-workout made a huge difference in my recovery',
            category: 'Nutrition',
            likes: 26,
            createdAt: new Date('2024-12-02T13:00:00').toISOString(),
            updatedAt: new Date('2024-12-02T13:00:00').toISOString(),
        },
        {
            userId: 3,
            authorName: 'Emma Davis',
            authorAvatar: 'https://i.pravatar.cc/150?img=3',
            content: 'Consistency beats intensity. Small daily efforts create massive results over time 💪',
            category: 'Motivation',
            likes: 40,
            createdAt: new Date('2024-12-03T07:20:00').toISOString(),
            updatedAt: new Date('2024-12-03T07:20:00').toISOString(),
        },
    ];

    await db.insert(communityPosts).values(samplePosts);
    
    console.log('✅ Community posts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});