import { db } from '@/db';
import { goals } from '@/db/schema';

async function main() {
    const sampleGoals = [
        {
            userId: 1,
            title: 'Lose 15 pounds',
            target: 140,
            current: 155,
            unit: 'lbs',
            deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'Weight Loss',
            status: 'in_progress',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            userId: 2,
            title: 'Run 5K under 30 minutes',
            target: 30,
            current: 35,
            unit: 'minutes',
            deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'Cardio Endurance',
            status: 'in_progress',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            userId: 3,
            title: 'Bench Press 200 lbs',
            target: 200,
            current: 165,
            unit: 'lbs',
            deadline: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'Strength',
            status: 'in_progress',
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            userId: 4,
            title: 'Touch toes without bending knees',
            target: 0,
            current: 5,
            unit: 'inches from toes',
            deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'Flexibility',
            status: 'in_progress',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            userId: 5,
            title: 'Drink 8 glasses of water daily',
            target: 64,
            current: 48,
            unit: 'oz per day',
            deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'Nutrition',
            status: 'in_progress',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            userId: 1,
            title: 'Complete 30-day yoga challenge',
            target: 30,
            current: 30,
            unit: 'days',
            deadline: new Date('2024-02-28').toISOString(),
            category: 'Flexibility',
            status: 'completed',
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            userId: 2,
            title: 'Squat 250 lbs for 5 reps',
            target: 250,
            current: 220,
            unit: 'lbs',
            deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'Strength',
            status: 'in_progress',
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-02-14').toISOString(),
        },
        {
            userId: 3,
            title: 'Reduce body fat to 15%',
            target: 15,
            current: 22,
            unit: 'percent',
            deadline: new Date(Date.now() + 150 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'Weight Loss',
            status: 'in_progress',
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            userId: 4,
            title: 'Run a half marathon',
            target: 13.1,
            current: 13.1,
            unit: 'miles',
            deadline: new Date('2024-03-15').toISOString(),
            category: 'Cardio Endurance',
            status: 'completed',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
        {
            userId: 5,
            title: 'Meal prep 5 days a week',
            target: 5,
            current: 3,
            unit: 'days per week',
            deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'Nutrition',
            status: 'in_progress',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            userId: 1,
            title: 'Achieve 10 pull-ups',
            target: 10,
            current: 10,
            unit: 'reps',
            deadline: new Date('2024-02-20').toISOString(),
            category: 'Strength',
            status: 'completed',
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            userId: 2,
            title: 'Learn swimming basics',
            target: 100,
            current: 25,
            unit: 'meters',
            deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
            category: 'Cardio Endurance',
            status: 'abandoned',
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
    ];

    await db.insert(goals).values(sampleGoals);
    
    console.log('✅ Goals seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});