import { db } from '@/db';
import { workouts } from '@/db/schema';

async function main() {
    const sampleWorkouts = [
        {
            userId: 1,
            workoutType: 'Running',
            durationMinutes: 45,
            caloriesBurned: 450,
            date: new Date('2024-11-15').toISOString(),
            notes: 'Morning run felt great! Hit new distance PR',
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-11-15').toISOString(),
        },
        {
            userId: 2,
            workoutType: 'Strength Training',
            durationMinutes: 60,
            caloriesBurned: 320,
            date: new Date('2024-11-18').toISOString(),
            notes: 'Upper body day - increased weight on bench press',
            createdAt: new Date('2024-11-18').toISOString(),
            updatedAt: new Date('2024-11-18').toISOString(),
        },
        {
            userId: 3,
            workoutType: 'Yoga',
            durationMinutes: 60,
            caloriesBurned: 220,
            date: new Date('2024-11-20').toISOString(),
            notes: 'Restorative yoga session, feeling more flexible',
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            userId: 4,
            workoutType: 'HIIT',
            durationMinutes: 30,
            caloriesBurned: 380,
            date: new Date('2024-11-22').toISOString(),
            notes: 'Intense 30min HIIT circuit, pushed through the burn!',
            createdAt: new Date('2024-11-22').toISOString(),
            updatedAt: new Date('2024-11-22').toISOString(),
        },
        {
            userId: 5,
            workoutType: 'Cycling',
            durationMinutes: 75,
            caloriesBurned: 600,
            date: new Date('2024-11-25').toISOString(),
            notes: 'Long bike ride through the park, beautiful weather',
            createdAt: new Date('2024-11-25').toISOString(),
            updatedAt: new Date('2024-11-25').toISOString(),
        },
        {
            userId: 1,
            workoutType: 'Swimming',
            durationMinutes: 45,
            caloriesBurned: 400,
            date: new Date('2024-11-28').toISOString(),
            notes: 'Freestyle laps, working on breathing technique',
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-11-28').toISOString(),
        },
        {
            userId: 2,
            workoutType: 'CrossFit',
            durationMinutes: 50,
            caloriesBurned: 520,
            date: new Date('2024-12-01').toISOString(),
            notes: 'WOD completed! Box jumps and kettlebell swings',
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            userId: 3,
            workoutType: 'Pilates',
            durationMinutes: 50,
            caloriesBurned: 250,
            date: new Date('2024-12-03').toISOString(),
            notes: 'Core-focused pilates, feeling the engagement',
            createdAt: new Date('2024-12-03').toISOString(),
            updatedAt: new Date('2024-12-03').toISOString(),
        },
        {
            userId: 4,
            workoutType: 'Running',
            durationMinutes: 35,
            caloriesBurned: 350,
            date: new Date('2024-12-05').toISOString(),
            notes: 'Easy recovery run, kept heart rate low',
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            userId: 5,
            workoutType: 'Strength Training',
            durationMinutes: 70,
            caloriesBurned: 350,
            date: new Date('2024-12-07').toISOString(),
            notes: 'Leg day - squats and deadlifts, feeling strong',
            createdAt: new Date('2024-12-07').toISOString(),
            updatedAt: new Date('2024-12-07').toISOString(),
        },
        {
            userId: 1,
            workoutType: 'HIIT',
            durationMinutes: 25,
            caloriesBurned: 320,
            date: new Date('2024-12-10').toISOString(),
            notes: 'Quick but effective HIIT session before work',
            createdAt: new Date('2024-12-10').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        {
            userId: 2,
            workoutType: 'Yoga',
            durationMinutes: 45,
            caloriesBurned: 180,
            date: new Date('2024-12-12').toISOString(),
            notes: 'Power yoga class, great for flexibility and strength',
            createdAt: new Date('2024-12-12').toISOString(),
            updatedAt: new Date('2024-12-12').toISOString(),
        },
        {
            userId: 3,
            workoutType: 'Cardio',
            durationMinutes: 40,
            caloriesBurned: 420,
            date: new Date('2024-12-14').toISOString(),
            notes: 'Elliptical workout while watching my favorite show',
            createdAt: new Date('2024-12-14').toISOString(),
            updatedAt: new Date('2024-12-14').toISOString(),
        },
        {
            userId: 4,
            workoutType: 'Swimming',
            durationMinutes: 50,
            caloriesBurned: 450,
            date: new Date('2024-12-16').toISOString(),
            notes: 'Mixed strokes today, butterfly getting better',
            createdAt: new Date('2024-12-16').toISOString(),
            updatedAt: new Date('2024-12-16').toISOString(),
        },
        {
            userId: 5,
            workoutType: 'CrossFit',
            durationMinutes: 55,
            caloriesBurned: 580,
            date: new Date('2024-12-18').toISOString(),
            notes: 'Partner WOD, love the team energy!',
            createdAt: new Date('2024-12-18').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            userId: 1,
            workoutType: 'Cycling',
            durationMinutes: 60,
            caloriesBurned: 480,
            date: new Date('2024-12-20').toISOString(),
            notes: 'Indoor cycling class, high intensity intervals',
            createdAt: new Date('2024-12-20').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            userId: 2,
            workoutType: 'Strength Training',
            durationMinutes: 65,
            caloriesBurned: 340,
            date: new Date('2024-12-22').toISOString(),
            notes: 'Full body workout, feeling pumped!',
            createdAt: new Date('2024-12-22').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            userId: 3,
            workoutType: 'Running',
            durationMinutes: 50,
            caloriesBurned: 500,
            date: new Date('2024-12-24').toISOString(),
            notes: 'Trail run with friends, challenging terrain',
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            userId: 4,
            workoutType: 'Pilates',
            durationMinutes: 55,
            caloriesBurned: 270,
            date: new Date('2024-12-26').toISOString(),
            notes: 'Reformer pilates, loved the full body burn',
            createdAt: new Date('2024-12-26').toISOString(),
            updatedAt: new Date('2024-12-26').toISOString(),
        },
        {
            userId: 5,
            workoutType: 'HIIT',
            durationMinutes: 35,
            caloriesBurned: 420,
            date: new Date('2024-12-28').toISOString(),
            notes: 'Burpees, mountain climbers, and jump squats - tough but rewarding',
            createdAt: new Date('2024-12-28').toISOString(),
            updatedAt: new Date('2024-12-28').toISOString(),
        },
        {
            userId: 1,
            workoutType: 'Strength Training',
            durationMinutes: 55,
            caloriesBurned: 300,
            date: new Date('2024-12-30').toISOString(),
            notes: 'Back and biceps day, hit new PR on pull-ups!',
            createdAt: new Date('2024-12-30').toISOString(),
            updatedAt: new Date('2024-12-30').toISOString(),
        },
        {
            userId: 2,
            workoutType: 'Cardio',
            durationMinutes: 45,
            caloriesBurned: 450,
            date: new Date('2025-01-02').toISOString(),
            notes: 'Stair climber workout, legs are on fire!',
            createdAt: new Date('2025-01-02').toISOString(),
            updatedAt: new Date('2025-01-02').toISOString(),
        },
        {
            userId: 3,
            workoutType: 'Swimming',
            durationMinutes: 40,
            caloriesBurned: 360,
            date: new Date('2025-01-04').toISOString(),
            notes: 'Water aerobics class, fun and effective',
            createdAt: new Date('2025-01-04').toISOString(),
            updatedAt: new Date('2025-01-04').toISOString(),
        },
        {
            userId: 4,
            workoutType: 'Yoga',
            durationMinutes: 70,
            caloriesBurned: 240,
            date: new Date('2025-01-06').toISOString(),
            notes: 'Vinyasa flow, amazing for mind and body',
            createdAt: new Date('2025-01-06').toISOString(),
            updatedAt: new Date('2025-01-06').toISOString(),
        },
        {
            userId: 5,
            workoutType: 'Running',
            durationMinutes: 90,
            caloriesBurned: 800,
            date: new Date('2025-01-08').toISOString(),
            notes: 'Long distance run preparation, training for half marathon!',
            createdAt: new Date('2025-01-08').toISOString(),
            updatedAt: new Date('2025-01-08').toISOString(),
        }
    ];

    await db.insert(workouts).values(sampleWorkouts);
    
    console.log('✅ Workouts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});